### ISSUE TITLE
Missing API

### ISSUE THREAD

**Issue by MattW86** [rcobelli/telephone-pictionary#1]
Hi,

I couldn't see the API for the Web Services. Maybe forgot to push? 

Thanks.

**Comment by rcobelli** [comment]
You're right! I had the backend in a separate repo and never added it to this one. I also added the database structure. 
[https://github.com/rcobelli/telephone-pictionary/commit/affefc3fe231d2a48d1b2b55564dedf2aba1fd4c](affefc3)
